# MCP Control Plane Configuration

server:
  host: "0.0.0.0"
  port: 8444
  workers: 1
  log_level: "INFO"
  cors_origins: []

# Authentication tokens for bridge clients
auth_tokens:
  - "dev-token-secure-string"
  - "prod-token-different-string"

# MCP servers to manage
mcp_servers:
  # Official MCP filesystem server
  - id: "filesystem"
    name: "MCP Filesystem Server"
    type: "npx"
    command: ["npx", "-y", "@modelcontextprotocol/server-filesystem", "/Users/vvishnu/Desktop"]
    cwd: null
    env: {}
    timeout: 30
    restart_on_failure: true
    enabled: true